{"name": "Проверка ошибки принятия заказа без id заказа", "status": "passed", "start": 1720188155532, "stop": 1720188155626, "uuid": "0115faa5-bbe5-43de-b3d1-0ad19ace37cc", "historyId": "4a91230f162896b047f6144bfe33162a", "testCaseId": "4a91230f162896b047f6144bfe33162a", "fullName": "tests.test_accept_order.test_accept_order_fail.TestAcceptOrderFail#test_accept_order_without_order_id", "labels": [{"name": "parentSuite", "value": "tests.test_accept_order"}, {"name": "suite", "value": "test_accept_order_fail"}, {"name": "subSuite", "value": "TestAcceptOrderFail"}, {"name": "host", "value": "DESKTOP-Q9FKTCA"}, {"name": "thread", "value": "11792-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order.test_accept_order_fail"}]}