{"name": "Проверка ошибки принятия заказа без id курьера", "status": "passed", "start": 1720032090108, "stop": 1720032090343, "uuid": "1f4c4164-c629-4761-914d-69618a079757", "historyId": "5c1e0c1c9af910be02b14550c5eebcc4", "testCaseId": "5c1e0c1c9af910be02b14550c5eebcc4", "fullName": "tests.test_accept_order.test_accept_order_fail.TestAcceptOrderFail#test_accept_order_without_courier_id", "labels": [{"name": "parentSuite", "value": "tests.test_accept_order"}, {"name": "suite", "value": "test_accept_order_fail"}, {"name": "subSuite", "value": "TestAcceptOrderFail"}, {"name": "host", "value": "DESKTOP-Q9FKTCA"}, {"name": "thread", "value": "1872-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order.test_accept_order_fail"}]}